name: chat_example
version: 6.8.2
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value:
    path: ../built_value
  shelf: ^0.7.3
  shelf_proxy:
  shelf_web_socket: ^0.2.2
  web_socket_channel: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator:
    path: ../built_value_generator
  pedantic: ^1.4.0
  test: ^1.0.0
